import React, { useState, useEffect } from 'react'
import Swal from "sweetalert2";

export default function IAResult() {

    document.title = "IA 1 Marks - Arman Nakhwa";

    let data =[
        {
          "RollNo": "1",
          "Name": "ANERAO AMOGH HEMANT",
          "IP_IA1": "15",
          "IP_IA2": "18",
          "IP_Average": "17",
          "CNS_IA1": "20",
          "CNS_IA2": "18",
          "CNS_Average": "19",
          "EEB_IA1": "18",
          "EEB_IA2": "17",
          "EEB_Average": "18",
          "SE_IA1": "18",
          "SE_IA2": "19",
          "SE_Average": "19",
          "CGMS_IA1": "15",
          "CGMS_IA2": "18",
          "CGMS_Average": "17"
        },
        {
          "RollNo": "2",
          "Name": "ARONDEKAR GANESH CHANDRAKANT",
          "IP_IA1": "19",
          "IP_IA2": "17",
          "IP_Average": "18",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "18",
          "EEB_IA2": "16",
          "EEB_Average": "17",
          "SE_IA1": "16",
          "SE_IA2": "18",
          "SE_Average": "17",
          "CGMS_IA1": "15",
          "CGMS_IA2": "18",
          "CGMS_Average": "17"
        },
        {
          "RollNo": "3",
          "Name": "BAGAVE RENUKA RAVINDRA",
          "IP_IA1": "20",
          "IP_IA2": "18",
          "IP_Average": "19",
          "CNS_IA1": "20",
          "CNS_IA2": "19",
          "CNS_Average": "20",
          "EEB_IA1": "17",
          "EEB_IA2": "19",
          "EEB_Average": "18",
          "SE_IA1": "18",
          "SE_IA2": "19",
          "SE_Average": "19",
          "CGMS_IA1": "16",
          "CGMS_IA2": "18",
          "CGMS_Average": "17"
        },
        {
          "RollNo": "4",
          "Name": "BHAGWAT ATHARVA SANTOSH",
          "IP_IA1": "19",
          "IP_IA2": "17",
          "IP_Average": "18",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "17",
          "EEB_IA2": "18",
          "EEB_Average": "18",
          "SE_IA1": "16",
          "SE_IA2": "18",
          "SE_Average": "17",
          "CGMS_IA1": "16",
          "CGMS_IA2": "18",
          "CGMS_Average": "17"
        },
        {
          "RollNo": "5",
          "Name": "BIRJE AAKANKSHA ANIL",
          "IP_IA1": "19",
          "IP_IA2": "16",
          "IP_Average": "18",
          "CNS_IA1": "18",
          "CNS_IA2": "17",
          "CNS_Average": "18",
          "EEB_IA1": "18",
          "EEB_IA2": "19",
          "EEB_Average": "19",
          "SE_IA1": "17",
          "SE_IA2": "14",
          "SE_Average": "16",
          "CGMS_IA1": "13",
          "CGMS_IA2": "17",
          "CGMS_Average": "15"
        },
        {
          "RollNo": "6",
          "Name": "BORKAR AFIYA AYUB",
          "IP_IA1": "20",
          "IP_IA2": "18",
          "IP_Average": "19",
          "CNS_IA1": "20",
          "CNS_IA2": "18",
          "CNS_Average": "19",
          "EEB_IA1": "19",
          "EEB_IA2": "20",
          "EEB_Average": "20",
          "SE_IA1": "19",
          "SE_IA2": "19",
          "SE_Average": "19",
          "CGMS_IA1": "19",
          "CGMS_IA2": "18",
          "CGMS_Average": "19"
        },
        {
          "RollNo": "7",
          "Name": "CHOUDHARY AJIT CHANDRAPAL",
          "IP_IA1": "18",
          "IP_IA2": "19",
          "IP_Average": "19",
          "CNS_IA1": "17",
          "CNS_IA2": "19",
          "CNS_Average": "18",
          "EEB_IA1": "16",
          "EEB_IA2": "20",
          "EEB_Average": "18",
          "SE_IA1": "13",
          "SE_IA2": "16",
          "SE_Average": "15",
          "CGMS_IA1": "16",
          "CGMS_IA2": "15",
          "CGMS_Average": "16"
        },
        {
          "RollNo": "8",
          "Name": "DANGE AARYA SANJAY",
          "IP_IA1": "20",
          "IP_IA2": "19",
          "IP_Average": "20",
          "CNS_IA1": "18",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "17",
          "EEB_IA2": "18",
          "EEB_Average": "18",
          "SE_IA1": "17",
          "SE_IA2": "19",
          "SE_Average": "18",
          "CGMS_IA1": "16",
          "CGMS_IA2": "19",
          "CGMS_Average": "18"
        },
        {
          "RollNo": "9",
          "Name": "DESAI SHRUTI SANTOSH",
          "IP_IA1": "20",
          "IP_IA2": "17",
          "IP_Average": "19",
          "CNS_IA1": "20",
          "CNS_IA2": "19",
          "CNS_Average": "20",
          "EEB_IA1": "17",
          "EEB_IA2": "19",
          "EEB_Average": "18",
          "SE_IA1": "16",
          "SE_IA2": "20",
          "SE_Average": "18",
          "CGMS_IA1": "18",
          "CGMS_IA2": "18",
          "CGMS_Average": "18"
        },
        {
          "RollNo": "10",
          "Name": "DHANGAT PRIYANKA RAMESH",
          "IP_IA1": "20",
          "IP_IA2": "19",
          "IP_Average": "20",
          "CNS_IA1": "20",
          "CNS_IA2": "19",
          "CNS_Average": "20",
          "EEB_IA1": "16",
          "EEB_IA2": "19",
          "EEB_Average": "18",
          "SE_IA1": "17",
          "SE_IA2": "19",
          "SE_Average": "18",
          "CGMS_IA1": "17",
          "CGMS_IA2": "17",
          "CGMS_Average": "17"
        },
        {
          "RollNo": "11",
          "Name": "DHURI NEHAL VASANT",
          "IP_IA1": "19",
          "IP_IA2": "17",
          "IP_Average": "18",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "17",
          "EEB_IA2": "18",
          "EEB_Average": "18",
          "SE_IA1": "16",
          "SE_IA2": "20",
          "SE_Average": "18",
          "CGMS_IA1": "18",
          "CGMS_IA2": "17",
          "CGMS_Average": "18"
        },
        {
          "RollNo": "12",
          "Name": "GARDE TANMAY PRAMOD",
          "IP_IA1": "19",
          "IP_IA2": "19",
          "IP_Average": "19",
          "CNS_IA1": "20",
          "CNS_IA2": "19",
          "CNS_Average": "20",
          "EEB_IA1": "16",
          "EEB_IA2": "19",
          "EEB_Average": "18",
          "SE_IA1": "19",
          "SE_IA2": "17",
          "SE_Average": "18",
          "CGMS_IA1": "16",
          "CGMS_IA2": "16",
          "CGMS_Average": "16"
        },
        {
          "RollNo": "13",
          "Name": "GURAV PRANALI GAJANAN",
          "IP_IA1": "19",
          "IP_IA2": "19",
          "IP_Average": "19",
          "CNS_IA1": "20",
          "CNS_IA2": "19",
          "CNS_Average": "20",
          "EEB_IA1": "19",
          "EEB_IA2": "20",
          "EEB_Average": "20",
          "SE_IA1": "19",
          "SE_IA2": "20",
          "SE_Average": "20",
          "CGMS_IA1": "18",
          "CGMS_IA2": "19",
          "CGMS_Average": "19"
        },
        {
          "RollNo": "14",
          "Name": "JADHAV PRAJAKTA DATTARAM",
          "IP_IA1": "19",
          "IP_IA2": "17",
          "IP_Average": "18",
          "CNS_IA1": "20",
          "CNS_IA2": "17",
          "CNS_Average": "19",
          "EEB_IA1": "16",
          "EEB_IA2": "18",
          "EEB_Average": "17",
          "SE_IA1": "17",
          "SE_IA2": "18",
          "SE_Average": "18",
          "CGMS_IA1": "13",
          "CGMS_IA2": "16",
          "CGMS_Average": "15"
        },
        {
          "RollNo": "15",
          "Name": "JADHAV PRATIK JIVAN",
          "IP_IA1": "17",
          "IP_IA2": "19",
          "IP_Average": "18",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "16",
          "EEB_IA2": "17",
          "EEB_Average": "17",
          "SE_IA1": "16",
          "SE_IA2": "18",
          "SE_Average": "17",
          "CGMS_IA1": "14",
          "CGMS_IA2": "17",
          "CGMS_Average": "16"
        },
        {
          "RollNo": "16",
          "Name": "JANGLE SUSHAMA DEOO",
          "IP_IA1": "20",
          "IP_IA2": "17",
          "IP_Average": "19",
          "CNS_IA1": "20",
          "CNS_IA2": "18",
          "CNS_Average": "19",
          "EEB_IA1": "18",
          "EEB_IA2": "19",
          "EEB_Average": "19",
          "SE_IA1": "17",
          "SE_IA2": "17",
          "SE_Average": "17",
          "CGMS_IA1": "13",
          "CGMS_IA2": "15",
          "CGMS_Average": "14"
        },
        {
          "RollNo": "17",
          "Name": "JAYGADE JANHAVI JEEVAN",
          "IP_IA1": "18",
          "IP_IA2": "17",
          "IP_Average": "18",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "18",
          "EEB_IA2": "19",
          "EEB_Average": "19",
          "SE_IA1": "17",
          "SE_IA2": "19",
          "SE_Average": "18",
          "CGMS_IA1": "15",
          "CGMS_IA2": "18",
          "CGMS_Average": "17"
        },
        {
          "RollNo": "18",
          "Name": "JOSHI MADHURA AVINASH",
          "IP_IA1": "19",
          "IP_IA2": "19",
          "IP_Average": "19",
          "CNS_IA1": "20",
          "CNS_IA2": "16",
          "CNS_Average": "18",
          "EEB_IA1": "17",
          "EEB_IA2": "19",
          "EEB_Average": "18",
          "SE_IA1": "17",
          "SE_IA2": "19",
          "SE_Average": "18",
          "CGMS_IA1": "17",
          "CGMS_IA2": "17",
          "CGMS_Average": "17"
        },
        {
          "RollNo": "19",
          "Name": "KADAM RUSHIKESH DATTATRAY",
          "IP_IA1": "20",
          "IP_IA2": "19",
          "IP_Average": "20",
          "CNS_IA1": "20",
          "CNS_IA2": "18",
          "CNS_Average": "19",
          "EEB_IA1": "18",
          "EEB_IA2": "20",
          "EEB_Average": "19",
          "SE_IA1": "17",
          "SE_IA2": "19",
          "SE_Average": "18",
          "CGMS_IA1": "18",
          "CGMS_IA2": "17",
          "CGMS_Average": "18"
        },
        {
          "RollNo": "20",
          "Name": "KAMBALE ASHISH ANIL",
          "IP_IA1": "19",
          "IP_IA2": "15",
          "IP_Average": "17",
          "CNS_IA1": "18",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "16",
          "EEB_IA2": "18",
          "EEB_Average": "17",
          "SE_IA1": "15",
          "SE_IA2": "16",
          "SE_Average": "16",
          "CGMS_IA1": "15",
          "CGMS_IA2": "15",
          "CGMS_Average": "15"
        },
        {
          "RollNo": "21",
          "Name": "KHAN TAUZ TANVEER",
          "IP_IA1": "19",
          "IP_IA2": "19",
          "IP_Average": "19",
          "CNS_IA1": "19",
          "CNS_IA2": "18",
          "CNS_Average": "19",
          "EEB_IA1": "17",
          "EEB_IA2": "20",
          "EEB_Average": "19",
          "SE_IA1": "18",
          "SE_IA2": "18",
          "SE_Average": "18",
          "CGMS_IA1": "17",
          "CGMS_IA2": "19",
          "CGMS_Average": "18"
        },
        {
          "RollNo": "22",
          "Name": "KHEDASKAR SHREYA SANJAY",
          "IP_IA1": "20",
          "IP_IA2": "17",
          "IP_Average": "19",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "18",
          "EEB_IA2": "19",
          "EEB_Average": "19",
          "SE_IA1": "18",
          "SE_IA2": "18",
          "SE_Average": "18",
          "CGMS_IA1": "17",
          "CGMS_IA2": "17",
          "CGMS_Average": "17"
        },
        {
          "RollNo": "23",
          "Name": "KHEDEKAR SOHAM UDAY",
          "IP_IA1": "14",
          "IP_IA2": "14",
          "IP_Average": "14",
          "CNS_IA1": "16",
          "CNS_IA2": "12",
          "CNS_Average": "14",
          "EEB_IA1": "AB",
          "EEB_IA2": "15",
          "EEB_Average": "8",
          "SE_IA1": "14",
          "SE_IA2": "13",
          "SE_Average": "14",
          "CGMS_IA1": "14",
          "CGMS_IA2": "16",
          "CGMS_Average": "15"
        },
        {
          "RollNo": "24",
          "Name": "KOLHATKAR ARPITA VILAS",
          "IP_IA1": "20",
          "IP_IA2": "20",
          "IP_Average": "20",
          "CNS_IA1": "19",
          "CNS_IA2": "18",
          "CNS_Average": "19",
          "EEB_IA1": "19",
          "EEB_IA2": "19",
          "EEB_Average": "19",
          "SE_IA1": "18",
          "SE_IA2": "20",
          "SE_Average": "19",
          "CGMS_IA1": "19",
          "CGMS_IA2": "17",
          "CGMS_Average": "18"
        },
        {
          "RollNo": "25",
          "Name": "KORAVI SOURABH SHIVAJI",
          "IP_IA1": "18",
          "IP_IA2": "19",
          "IP_Average": "19",
          "CNS_IA1": "20",
          "CNS_IA2": "16",
          "CNS_Average": "18",
          "EEB_IA1": "17",
          "EEB_IA2": "19",
          "EEB_Average": "18",
          "SE_IA1": "16",
          "SE_IA2": "20",
          "SE_Average": "18",
          "CGMS_IA1": "18",
          "CGMS_IA2": "18",
          "CGMS_Average": "18"
        },
        {
          "RollNo": "26",
          "Name": "KUMBHAR RUTUJA RAJENDRA",
          "IP_IA1": "20",
          "IP_IA2": "18",
          "IP_Average": "19",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "17",
          "EEB_IA2": "16",
          "EEB_Average": "17",
          "SE_IA1": "16",
          "SE_IA2": "14",
          "SE_Average": "15",
          "CGMS_IA1": "15",
          "CGMS_IA2": "16",
          "CGMS_Average": "16"
        },
        {
          "RollNo": "27",
          "Name": "LAKHAN YOGESHRI PRAKASH PRIYANKA",
          "IP_IA1": "18",
          "IP_IA2": "17",
          "IP_Average": "18",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "18",
          "EEB_IA2": "18",
          "EEB_Average": "18",
          "SE_IA1": "17",
          "SE_IA2": "18",
          "SE_Average": "18",
          "CGMS_IA1": "18",
          "CGMS_IA2": "18",
          "CGMS_Average": "18"
        },
        {
          "RollNo": "28",
          "Name": "LELE JANHAVI MAHESH",
          "IP_IA1": "18",
          "IP_IA2": "18",
          "IP_Average": "18",
          "CNS_IA1": "19",
          "CNS_IA2": "17",
          "CNS_Average": "18",
          "EEB_IA1": "17",
          "EEB_IA2": "16",
          "EEB_Average": "17",
          "SE_IA1": "19",
          "SE_IA2": "15",
          "SE_Average": "17",
          "CGMS_IA1": "18",
          "CGMS_IA2": "14",
          "CGMS_Average": "16"
        },
        {
          "RollNo": "29",
          "Name": "MADKAIKAR HARSH MILIND",
          "IP_IA1": "20",
          "IP_IA2": "18",
          "IP_Average": "19",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "17",
          "EEB_IA2": "17",
          "EEB_Average": "17",
          "SE_IA1": "17",
          "SE_IA2": "18",
          "SE_Average": "18",
          "CGMS_IA1": "19",
          "CGMS_IA2": "19",
          "CGMS_Average": "19"
        },
        {
          "RollNo": "30",
          "Name": "MALJI ATHARVA BALKRISHNA",
          "IP_IA1": "20",
          "IP_IA2": "20",
          "IP_Average": "20",
          "CNS_IA1": "20",
          "CNS_IA2": "18",
          "CNS_Average": "19",
          "EEB_IA1": "16",
          "EEB_IA2": "18",
          "EEB_Average": "17",
          "SE_IA1": "18",
          "SE_IA2": "18",
          "SE_Average": "18",
          "CGMS_IA1": "17",
          "CGMS_IA2": "18",
          "CGMS_Average": "18"
        },
        {
          "RollNo": "31",
          "Name": "MANE SUPRIYA NANDKUMAR",
          "IP_IA1": "14",
          "IP_IA2": "17",
          "IP_Average": "16",
          "CNS_IA1": "18",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "16",
          "EEB_IA2": "18",
          "EEB_Average": "17",
          "SE_IA1": "17",
          "SE_IA2": "17",
          "SE_Average": "17",
          "CGMS_IA1": "12",
          "CGMS_IA2": "16",
          "CGMS_Average": "14"
        },
        {
          "RollNo": "32",
          "Name": "MARAGALE TUSHAR NARAYAN",
          "IP_IA1": "20",
          "IP_IA2": "17",
          "IP_Average": "19",
          "CNS_IA1": "20",
          "CNS_IA2": "19",
          "CNS_Average": "20",
          "EEB_IA1": "17",
          "EEB_IA2": "20",
          "EEB_Average": "19",
          "SE_IA1": "17",
          "SE_IA2": "18",
          "SE_Average": "18",
          "CGMS_IA1": "14",
          "CGMS_IA2": "17",
          "CGMS_Average": "16"
        },
        {
          "RollNo": "33",
          "Name": "MATKAR SAIRAJ SANJAY",
          "IP_IA1": "19",
          "IP_IA2": "19",
          "IP_Average": "19",
          "CNS_IA1": "20",
          "CNS_IA2": "19",
          "CNS_Average": "20",
          "EEB_IA1": "16",
          "EEB_IA2": "17",
          "EEB_Average": "17",
          "SE_IA1": "18",
          "SE_IA2": "17",
          "SE_Average": "18",
          "CGMS_IA1": "15",
          "CGMS_IA2": "19",
          "CGMS_Average": "17"
        },
        {
          "RollNo": "34",
          "Name": "MESTRI ATHARVA CHANDRASHEKHAR",
          "IP_IA1": "19",
          "IP_IA2": "20",
          "IP_Average": "20",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "17",
          "EEB_IA2": "17",
          "EEB_Average": "17",
          "SE_IA1": "14",
          "SE_IA2": "16",
          "SE_Average": "15",
          "CGMS_IA1": "15",
          "CGMS_IA2": "17",
          "CGMS_Average": "16"
        },
        {
          "RollNo": "35",
          "Name": "MHADE NEHA ASHOK",
          "IP_IA1": "19",
          "IP_IA2": "15",
          "IP_Average": "17",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "18",
          "EEB_IA2": "18",
          "EEB_Average": "18",
          "SE_IA1": "17",
          "SE_IA2": "18",
          "SE_Average": "18",
          "CGMS_IA1": "14",
          "CGMS_IA2": "18",
          "CGMS_Average": "16"
        },
        {
          "RollNo": "36",
          "Name": "MHADGUT ASAVARI PRADEEPKUMAR",
          "IP_IA1": "20",
          "IP_IA2": "17",
          "IP_Average": "19",
          "CNS_IA1": "19",
          "CNS_IA2": "15",
          "CNS_Average": "17",
          "EEB_IA1": "18",
          "EEB_IA2": "17",
          "EEB_Average": "18",
          "SE_IA1": "17",
          "SE_IA2": "16",
          "SE_Average": "17",
          "CGMS_IA1": "15",
          "CGMS_IA2": "16",
          "CGMS_Average": "16"
        },
        {
          "RollNo": "37",
          "Name": "MIRASHI PANKAJ SANTOSH",
          "IP_IA1": "19",
          "IP_IA2": "17",
          "IP_Average": "18",
          "CNS_IA1": "18",
          "CNS_IA2": "17",
          "CNS_Average": "18",
          "EEB_IA1": "18",
          "EEB_IA2": "16",
          "EEB_Average": "17",
          "SE_IA1": "15",
          "SE_IA2": "16",
          "SE_Average": "16",
          "CGMS_IA1": "12",
          "CGMS_IA2": "16",
          "CGMS_Average": "14"
        },
        {
          "RollNo": "38",
          "Name": "MUKADAM AFRAH MUSHTAQ",
          "IP_IA1": "19",
          "IP_IA2": "19",
          "IP_Average": "19",
          "CNS_IA1": "20",
          "CNS_IA2": "19",
          "CNS_Average": "20",
          "EEB_IA1": "18",
          "EEB_IA2": "20",
          "EEB_Average": "19",
          "SE_IA1": "19",
          "SE_IA2": "20",
          "SE_Average": "20",
          "CGMS_IA1": "20",
          "CGMS_IA2": "18",
          "CGMS_Average": "19"
        },
        {
          "RollNo": "39",
          "Name": "MUKADAM MARUFA IRFAN",
          "IP_IA1": "20",
          "IP_IA2": "19",
          "IP_Average": "20",
          "CNS_IA1": "20",
          "CNS_IA2": "19",
          "CNS_Average": "20",
          "EEB_IA1": "17",
          "EEB_IA2": "20",
          "EEB_Average": "19",
          "SE_IA1": "19",
          "SE_IA2": "20",
          "SE_Average": "20",
          "CGMS_IA1": "20",
          "CGMS_IA2": "20",
          "CGMS_Average": "20"
        },
        {
          "RollNo": "40",
          "Name": "MUKADAM SUHA MOHAMED HUSAIN",
          "IP_IA1": "20",
          "IP_IA2": "18",
          "IP_Average": "19",
          "CNS_IA1": "20",
          "CNS_IA2": "18",
          "CNS_Average": "19",
          "EEB_IA1": "18",
          "EEB_IA2": "19",
          "EEB_Average": "19",
          "SE_IA1": "19",
          "SE_IA2": "20",
          "SE_Average": "20",
          "CGMS_IA1": "17",
          "CGMS_IA2": "18",
          "CGMS_Average": "18"
        },
        {
          "RollNo": "41",
          "Name": "MUNGEKAR MANTHAN BHALCHANDRA",
          "IP_IA1": "18",
          "IP_IA2": "19",
          "IP_Average": "19",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "17",
          "EEB_IA2": "18",
          "EEB_Average": "18",
          "SE_IA1": "16",
          "SE_IA2": "18",
          "SE_Average": "17",
          "CGMS_IA1": "17",
          "CGMS_IA2": "15",
          "CGMS_Average": "16"
        },
        {
          "RollNo": "42",
          "Name": "NABAR PRADNYA KISHOR",
          "IP_IA1": "18",
          "IP_IA2": "19",
          "IP_Average": "19",
          "CNS_IA1": "19",
          "CNS_IA2": "18",
          "CNS_Average": "19",
          "EEB_IA1": "18",
          "EEB_IA2": "19",
          "EEB_Average": "19",
          "SE_IA1": "17",
          "SE_IA2": "19",
          "SE_Average": "18",
          "CGMS_IA1": "18",
          "CGMS_IA2": "17",
          "CGMS_Average": "18"
        },
        {
          "RollNo": "43",
          "Name": "NACHANKAR GURUPRASAD SUBHASH SHUBHANGI",
          "IP_IA1": "19",
          "IP_IA2": "18",
          "IP_Average": "19",
          "CNS_IA1": "19",
          "CNS_IA2": "15",
          "CNS_Average": "17",
          "EEB_IA1": "17",
          "EEB_IA2": "17",
          "EEB_Average": "17",
          "SE_IA1": "16",
          "SE_IA2": "19",
          "SE_Average": "18",
          "CGMS_IA1": "16",
          "CGMS_IA2": "17",
          "CGMS_Average": "17"
        },
        {
          "RollNo": "44",
          "Name": "NACHANKAR VAISHNAVI NILESH",
          "IP_IA1": "20",
          "IP_IA2": "19",
          "IP_Average": "20",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "17",
          "EEB_IA2": "19",
          "EEB_Average": "18",
          "SE_IA1": "16",
          "SE_IA2": "18",
          "SE_Average": "17",
          "CGMS_IA1": "17",
          "CGMS_IA2": "16",
          "CGMS_Average": "17"
        },
        {
          "RollNo": "45",
          "Name": "NAKHWA ARMAN ANIS",
          "IP_IA1": "20",
          "IP_IA2": "20",
          "IP_Average": "20",
          "CNS_IA1": "20",
          "CNS_IA2": "18",
          "CNS_Average": "19",
          "EEB_IA1": "17",
          "EEB_IA2": "18",
          "EEB_Average": "18",
          "SE_IA1": "18",
          "SE_IA2": "18",
          "SE_Average": "18",
          "CGMS_IA1": "18",
          "CGMS_IA2": "19",
          "CGMS_Average": "19"
        },
        {
          "RollNo": "46",
          "Name": "NALAWADE SAYALI UMESH",
          "IP_IA1": "20",
          "IP_IA2": "17",
          "IP_Average": "19",
          "CNS_IA1": "20",
          "CNS_IA2": "19",
          "CNS_Average": "20",
          "EEB_IA1": "18",
          "EEB_IA2": "18",
          "EEB_Average": "18",
          "SE_IA1": "17",
          "SE_IA2": "18",
          "SE_Average": "18",
          "CGMS_IA1": "18",
          "CGMS_IA2": "19",
          "CGMS_Average": "19"
        },
        {
          "RollNo": "47",
          "Name": "NARKAR RAJ VINOD",
          "IP_IA1": "19",
          "IP_IA2": "18",
          "IP_Average": "19",
          "CNS_IA1": "20",
          "CNS_IA2": "19",
          "CNS_Average": "20",
          "EEB_IA1": "18",
          "EEB_IA2": "18",
          "EEB_Average": "18",
          "SE_IA1": "17",
          "SE_IA2": "18",
          "SE_Average": "18",
          "CGMS_IA1": "17",
          "CGMS_IA2": "18",
          "CGMS_Average": "18"
        },
        {
          "RollNo": "48",
          "Name": "NARVEKAR YASH NAGESH",
          "IP_IA1": "19",
          "IP_IA2": "19",
          "IP_Average": "19",
          "CNS_IA1": "19",
          "CNS_IA2": "16",
          "CNS_Average": "18",
          "EEB_IA1": "18",
          "EEB_IA2": "17",
          "EEB_Average": "18",
          "SE_IA1": "14",
          "SE_IA2": "16",
          "SE_Average": "15",
          "CGMS_IA1": "12",
          "CGMS_IA2": "18",
          "CGMS_Average": "15"
        },
        {
          "RollNo": "49",
          "Name": "PALAV PRATHAMESH PRADEEP",
          "IP_IA1": "19",
          "IP_IA2": "17",
          "IP_Average": "18",
          "CNS_IA1": "18",
          "CNS_IA2": "18",
          "CNS_Average": "18",
          "EEB_IA1": "17",
          "EEB_IA2": "17",
          "EEB_Average": "17",
          "SE_IA1": "16",
          "SE_IA2": "17",
          "SE_Average": "17",
          "CGMS_IA1": "16",
          "CGMS_IA2": "17",
          "CGMS_Average": "17"
        },
        {
          "RollNo": "50",
          "Name": "PANCHAL MRUNAL SANDIP",
          "IP_IA1": "19",
          "IP_IA2": "18",
          "IP_Average": "19",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "17",
          "EEB_IA2": "19",
          "EEB_Average": "18",
          "SE_IA1": "17",
          "SE_IA2": "18",
          "SE_Average": "18",
          "CGMS_IA1": "17",
          "CGMS_IA2": "17",
          "CGMS_Average": "17"
        },
        {
          "RollNo": "51",
          "Name": "PARAB SHANKAR SITARAM",
          "IP_IA1": "20",
          "IP_IA2": "19",
          "IP_Average": "20",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "18",
          "EEB_IA2": "18",
          "EEB_Average": "18",
          "SE_IA1": "16",
          "SE_IA2": "19",
          "SE_Average": "18",
          "CGMS_IA1": "16",
          "CGMS_IA2": "16",
          "CGMS_Average": "16"
        },
        {
          "RollNo": "52",
          "Name": "PARANJAPE NIVEDITA PRASHANT",
          "IP_IA1": "20",
          "IP_IA2": "19",
          "IP_Average": "20",
          "CNS_IA1": "20",
          "CNS_IA2": "18",
          "CNS_Average": "19",
          "EEB_IA1": "18",
          "EEB_IA2": "19",
          "EEB_Average": "19",
          "SE_IA1": "20",
          "SE_IA2": "19",
          "SE_Average": "20",
          "CGMS_IA1": "19",
          "CGMS_IA2": "18",
          "CGMS_Average": "19"
        },
        {
          "RollNo": "53",
          "Name": "PARANJAPE PRATHAMESH VILAS",
          "IP_IA1": "20",
          "IP_IA2": "19",
          "IP_Average": "20",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "17",
          "EEB_IA2": "20",
          "EEB_Average": "19",
          "SE_IA1": "15",
          "SE_IA2": "16",
          "SE_Average": "16",
          "CGMS_IA1": "17",
          "CGMS_IA2": "18",
          "CGMS_Average": "18"
        },
        {
          "RollNo": "54",
          "Name": "PARDESHI ASHISH KISHORSING YOGITABAI",
          "IP_IA1": "17",
          "IP_IA2": "19",
          "IP_Average": "18",
          "CNS_IA1": "18",
          "CNS_IA2": "15",
          "CNS_Average": "17",
          "EEB_IA1": "18",
          "EEB_IA2": "12",
          "EEB_Average": "15",
          "SE_IA1": "15",
          "SE_IA2": "14",
          "SE_Average": "15",
          "CGMS_IA1": "12",
          "CGMS_IA2": "18",
          "CGMS_Average": "15"
        },
        {
          "RollNo": "55",
          "Name": "PATANKAR PRIYANKA VIJAY",
          "IP_IA1": "20",
          "IP_IA2": "20",
          "IP_Average": "20",
          "CNS_IA1": "18",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "18",
          "EEB_IA2": "20",
          "EEB_Average": "19",
          "SE_IA1": "17",
          "SE_IA2": "17",
          "SE_Average": "17",
          "CGMS_IA1": "16",
          "CGMS_IA2": "16",
          "CGMS_Average": "16"
        },
        {
          "RollNo": "56",
          "Name": "PATIL MADHURA DATTATRAY",
          "IP_IA1": "20",
          "IP_IA2": "19",
          "IP_Average": "20",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "18",
          "EEB_IA2": "19",
          "EEB_Average": "19",
          "SE_IA1": "17",
          "SE_IA2": "18",
          "SE_Average": "18",
          "CGMS_IA1": "18",
          "CGMS_IA2": "18",
          "CGMS_Average": "18"
        },
        {
          "RollNo": "57",
          "Name": "PAWAR SAYALI DILIP",
          "IP_IA1": "20",
          "IP_IA2": "17",
          "IP_Average": "19",
          "CNS_IA1": "19",
          "CNS_IA2": "17",
          "CNS_Average": "18",
          "EEB_IA1": "17",
          "EEB_IA2": "18",
          "EEB_Average": "18",
          "SE_IA1": "17",
          "SE_IA2": "16",
          "SE_Average": "17",
          "CGMS_IA1": "17",
          "CGMS_IA2": "17",
          "CGMS_Average": "17"
        },
        {
          "RollNo": "58",
          "Name": "PHADNIS ANTARA SUNIT",
          "IP_IA1": "20",
          "IP_IA2": "18",
          "IP_Average": "19",
          "CNS_IA1": "20",
          "CNS_IA2": "17",
          "CNS_Average": "19",
          "EEB_IA1": "17",
          "EEB_IA2": "18",
          "EEB_Average": "18",
          "SE_IA1": "19",
          "SE_IA2": "20",
          "SE_Average": "20",
          "CGMS_IA1": "18",
          "CGMS_IA2": "18",
          "CGMS_Average": "18"
        },
        {
          "RollNo": "59",
          "Name": "PRABHU LAKSHITA RAJENDRAKUMAR",
          "IP_IA1": "20",
          "IP_IA2": "16",
          "IP_Average": "18",
          "CNS_IA1": "20",
          "CNS_IA2": "19",
          "CNS_Average": "20",
          "EEB_IA1": "18",
          "EEB_IA2": "17",
          "EEB_Average": "18",
          "SE_IA1": "17",
          "SE_IA2": "16",
          "SE_Average": "17",
          "CGMS_IA1": "15",
          "CGMS_IA2": "18",
          "CGMS_Average": "17"
        },
        {
          "RollNo": "60",
          "Name": "RAHUL KAUSHAL PRASAD",
          "IP_IA1": "20",
          "IP_IA2": "17",
          "IP_Average": "19",
          "CNS_IA1": "18",
          "CNS_IA2": "18",
          "CNS_Average": "18",
          "EEB_IA1": "17",
          "EEB_IA2": "19",
          "EEB_Average": "18",
          "SE_IA1": "18",
          "SE_IA2": "18",
          "SE_Average": "18",
          "CGMS_IA1": "18",
          "CGMS_IA2": "17",
          "CGMS_Average": "18"
        },
        {
          "RollNo": "61",
          "Name": "RAIN PRANJAL PRAVIN",
          "IP_IA1": "16",
          "IP_IA2": "17",
          "IP_Average": "17",
          "CNS_IA1": "18",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "18",
          "EEB_IA2": "19",
          "EEB_Average": "19",
          "SE_IA1": "18",
          "SE_IA2": "19",
          "SE_Average": "19",
          "CGMS_IA1": "12",
          "CGMS_IA2": "15",
          "CGMS_Average": "14"
        },
        {
          "RollNo": "62",
          "Name": "RAJAM BHUSHAN RATNAKAR",
          "IP_IA1": "20",
          "IP_IA2": "18",
          "IP_Average": "19",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "17",
          "EEB_IA2": "20",
          "EEB_Average": "19",
          "SE_IA1": "18",
          "SE_IA2": "19",
          "SE_Average": "19",
          "CGMS_IA1": "19",
          "CGMS_IA2": "18",
          "CGMS_Average": "19"
        },
        {
          "RollNo": "63",
          "Name": "RANE PRATHAMESH VILAS",
          "IP_IA1": "20",
          "IP_IA2": "18",
          "IP_Average": "19",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "17",
          "EEB_IA2": "18",
          "EEB_Average": "18",
          "SE_IA1": "18",
          "SE_IA2": "17",
          "SE_Average": "18",
          "CGMS_IA1": "14",
          "CGMS_IA2": "18",
          "CGMS_Average": "16"
        },
        {
          "RollNo": "64",
          "Name": "RANSHUR PRATIKSHA DILIP",
          "IP_IA1": "20",
          "IP_IA2": "19",
          "IP_Average": "20",
          "CNS_IA1": "20",
          "CNS_IA2": "19",
          "CNS_Average": "20",
          "EEB_IA1": "17",
          "EEB_IA2": "19",
          "EEB_Average": "18",
          "SE_IA1": "18",
          "SE_IA2": "18",
          "SE_Average": "18",
          "CGMS_IA1": "18",
          "CGMS_IA2": "18",
          "CGMS_Average": "18"
        },
        {
          "RollNo": "65",
          "Name": "SALGAONKAR SHWETA SHARAD",
          "IP_IA1": "19",
          "IP_IA2": "20",
          "IP_Average": "20",
          "CNS_IA1": "18",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "18",
          "EEB_IA2": "18",
          "EEB_Average": "18",
          "SE_IA1": "16",
          "SE_IA2": "16",
          "SE_Average": "16",
          "CGMS_IA1": "18",
          "CGMS_IA2": "19",
          "CGMS_Average": "19"
        },
        {
          "RollNo": "66",
          "Name": "SAWANT ASAWARI SHAILENDRA",
          "IP_IA1": "20",
          "IP_IA2": "20",
          "IP_Average": "20",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "17",
          "EEB_IA2": "20",
          "EEB_Average": "19",
          "SE_IA1": "17",
          "SE_IA2": "15",
          "SE_Average": "16",
          "CGMS_IA1": "15",
          "CGMS_IA2": "18",
          "CGMS_Average": "17"
        },
        {
          "RollNo": "67",
          "Name": "SAWANT DNYANESH DHANANJAY",
          "IP_IA1": "19",
          "IP_IA2": "19",
          "IP_Average": "19",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "18",
          "EEB_IA2": "18",
          "EEB_Average": "18",
          "SE_IA1": "16",
          "SE_IA2": "15",
          "SE_Average": "16",
          "CGMS_IA1": "16",
          "CGMS_IA2": "17",
          "CGMS_Average": "17"
        },
        {
          "RollNo": "68",
          "Name": "SHINGARE PRANALI DILIP",
          "IP_IA1": "19",
          "IP_IA2": "17",
          "IP_Average": "18",
          "CNS_IA1": "20",
          "CNS_IA2": "19",
          "CNS_Average": "20",
          "EEB_IA1": "18",
          "EEB_IA2": "18",
          "EEB_Average": "18",
          "SE_IA1": "19",
          "SE_IA2": "18",
          "SE_Average": "19",
          "CGMS_IA1": "17",
          "CGMS_IA2": "19",
          "CGMS_Average": "18"
        },
        {
          "RollNo": "69",
          "Name": "SHIRGAONKAR VED SAGAR",
          "IP_IA1": "19",
          "IP_IA2": "19",
          "IP_Average": "19",
          "CNS_IA1": "20",
          "CNS_IA2": "17",
          "CNS_Average": "19",
          "EEB_IA1": "18",
          "EEB_IA2": "19",
          "EEB_Average": "19",
          "SE_IA1": "17",
          "SE_IA2": "18",
          "SE_Average": "18",
          "CGMS_IA1": "19",
          "CGMS_IA2": "17",
          "CGMS_Average": "18"
        },
        {
          "RollNo": "70",
          "Name": "SOLKAR RIFAH MUNAF",
          "IP_IA1": "20",
          "IP_IA2": "18",
          "IP_Average": "19",
          "CNS_IA1": "20",
          "CNS_IA2": "18",
          "CNS_Average": "19",
          "EEB_IA1": "18",
          "EEB_IA2": "18",
          "EEB_Average": "18",
          "SE_IA1": "19",
          "SE_IA2": "19",
          "SE_Average": "19",
          "CGMS_IA1": "19",
          "CGMS_IA2": "19",
          "CGMS_Average": "19"
        },
        {
          "RollNo": "71",
          "Name": "SURVE SAKSHI DEEPAK",
          "IP_IA1": "20",
          "IP_IA2": "19",
          "IP_Average": "20",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "17",
          "EEB_IA2": "18",
          "EEB_Average": "18",
          "SE_IA1": "15",
          "SE_IA2": "18",
          "SE_Average": "17",
          "CGMS_IA1": "15",
          "CGMS_IA2": "19",
          "CGMS_Average": "17"
        },
        {
          "RollNo": "72",
          "Name": "TAMHANEKAR MAHADEV VIJAY",
          "IP_IA1": "20",
          "IP_IA2": "20",
          "IP_Average": "20",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "17",
          "EEB_IA2": "18",
          "EEB_Average": "18",
          "SE_IA1": "17",
          "SE_IA2": "17",
          "SE_Average": "17",
          "CGMS_IA1": "15",
          "CGMS_IA2": "18",
          "CGMS_Average": "17"
        },
        {
          "RollNo": "73",
          "Name": "TEMBE AKSHAY ANAND",
          "IP_IA1": "20",
          "IP_IA2": "19",
          "IP_Average": "20",
          "CNS_IA1": "19",
          "CNS_IA2": "19",
          "CNS_Average": "19",
          "EEB_IA1": "17",
          "EEB_IA2": "18",
          "EEB_Average": "18",
          "SE_IA1": "16",
          "SE_IA2": "17",
          "SE_Average": "17",
          "CGMS_IA1": "15",
          "CGMS_IA2": "18",
          "CGMS_Average": "17"
        },
        {
          "RollNo": "74",
          "Name": "UPPARA KAKULA KAVYASHREE RAMESH",
          "IP_IA1": "18",
          "IP_IA2": "20",
          "IP_Average": "19",
          "CNS_IA1": "19",
          "CNS_IA2": "17",
          "CNS_Average": "18",
          "EEB_IA1": "16",
          "EEB_IA2": "19",
          "EEB_Average": "18",
          "SE_IA1": "16",
          "SE_IA2": "18",
          "SE_Average": "17",
          "CGMS_IA1": "15",
          "CGMS_IA2": "18",
          "CGMS_Average": "17"
        },
        {
          "RollNo": "75",
          "Name": "VASKAR RUTIK RAVINDRA",
          "IP_IA1": "18",
          "IP_IA2": "17",
          "IP_Average": "18",
          "CNS_IA1": "19",
          "CNS_IA2": "17",
          "CNS_Average": "18",
          "EEB_IA1": "17",
          "EEB_IA2": "19",
          "EEB_Average": "18",
          "SE_IA1": "18",
          "SE_IA2": "16",
          "SE_Average": "17",
          "CGMS_IA1": "13",
          "CGMS_IA2": "19",
          "CGMS_Average": "16"
        },
        {
          "RollNo": "76",
          "Name": "WANIVDEKAR TANVI PRASHANT PRANJALI",
          "IP_IA1": "19",
          "IP_IA2": "19",
          "IP_Average": "19",
          "CNS_IA1": "18",
          "CNS_IA2": "16",
          "CNS_Average": "17",
          "EEB_IA1": "17",
          "EEB_IA2": "19",
          "EEB_Average": "18",
          "SE_IA1": "15",
          "SE_IA2": "18",
          "SE_Average": "17",
          "CGMS_IA1": "10",
          "CGMS_IA2": "19",
          "CGMS_Average": "15"
        }
      ];
      

    let [IAResultData, setIAResultData] = useState([]);
    let [sname, setsname] = useState("");


    useEffect(() => {
        setIAResultData(data);
        // eslint-disable-next-line 
    }, [])

    function searchs(e) {

        setsname(e.target.value);
    }

    function rankwise() {
        setsname("");
        Swal.fire({
            title: 'Dont Worry..read below Quote',
            icon: "warning",
            dangerMode: true,
            text: "Study for Knowledge,not for marks.if you have the knowledge,you will get the success.",
        });

        let s3 = data.sort(function (a, b) {
            let d1 = parseInt(a.IP_Average) + parseInt(a.CNS_Average) + parseInt(a.EEB_Average) + parseInt(a.SE_Average) + parseInt(a.CGMS_Average);
            let d2 = parseInt(b.IP_Average) + parseInt(b.CNS_Average) + parseInt(b.EEB_Average) + parseInt(b.SE_Average) + parseInt(b.CGMS_Average);
            return d2 - d1;
        });
        setIAResultData(s3);

        var elmnt = document.getElementById("firstdata");
        elmnt.scrollTop = 0;
    }




    return (
        <div className="overflow-hidden mb-2" style={{ height: "90vh" }}>
            <div className="position-sticky text-center text-white bg-danger p-2">Result is already send in our WhatsApp Group

                <input className="form-control my-2" type="search" onChange={searchs} value={sname} placeholder="Enter your name" aria-label="Search" />

            </div>
            <div className="overflow-auto" id="firstdata" style={{ maxHeight: "80%" }}>
                {
                    // eslint-disable-next-line 
                    IAResultData.filter((val) => {
                        if (sname === "") {
                            return val
                        }
                        else if (val.Name.toLowerCase().includes(sname.toLowerCase())) {
                            return val;
                        }

                    }).map((d, index) => {
                        return (
                            <div className="container p-3 my-3 bg-light text-dark" key={d.NAME}>
                                <h5 className="rankno">{index + 1}</h5>
                                <b style={{fontSize:'20px'}}>Name:</b> {d.Name} <br />
                                <b style={{fontSize:'20px'}}>Roll No:</b> {d.RollNo}<br />
                                <b>IP IA 1:</b> {d.IP_IA1}<br /> 
                                <b>IP IA 2:</b> {d.IP_IA2}<br /> 
                                <b style={{fontSize:'20px'}}>IP IA Average:</b> {d.IP_Average}<br /> 
                                <b>CNS IA 1:</b> {d.CNS_IA1}<br />
                                <b>CNS IA 2:</b> {d.CNS_IA2}<br />       
                                <b style={{fontSize:'20px'}}>CNS IA Average:</b> {d.CNS_Average}<br />       
                                <b>EEB IA 1:</b> {d.EEB_IA1}<br />
                                <b>EEB IA 2:</b> {d.EEB_IA2}<br />
                                <b style={{fontSize:'20px'}}>EEB IA Average:</b> {d.EEB_Average}<br />
                                <b>SE IA 1:</b> {d.SE_IA1}<br />
                                <b>SE IA 2:</b> {d.SE_IA2}<br />
                                <b style={{fontSize:'20px'}}>SE IA Average:</b> {d.SE_Average}<br />
                                <b>CGMS IA 1:</b> {d.CGMS_IA1}<br />
                                <b>CGMS IA 2:</b> {d.CGMS_IA2}<br />
                                <b style={{fontSize:'20px'}}>CGMS IA Average:</b> {d.CGMS_Average}<br />
                                <h1>Total:{parseInt(d.IP_Average) + parseInt(d.CNS_Average) + parseInt(d.EEB_Average) + parseInt(d.SE_Average) + parseInt(d.CGMS_Average)}/100 </h1><br />
                           
                            </div>   
                        );
                    })}

            </div>
            <button type="button" className="btn btn-danger rw" onClick={rankwise}>Rank Wise Result</button>


        </div>
    )
}
